### ISSUE TITLE
Pathfinding for miner1cart

### ISSUE THREAD

**Issue by jamesgraves** [jamesgraves/bonzAI#6]
The cart will often not choose the path to the energy source area via a road which exists, but instead head through the swamps.  Heading out to the energy source, it goes overland and through the swamp, but on the return trip, it follows the road.

Interestingly, the swamps don't seem the slow down the creep as much as expected, it is still moving once per tick.  Is this a bug with screeps itself?

**Comment by bonzaiferroni** [comment]
Yeah this is actually a "feature not a bug", empty carry parts and move parts do not generate fatigue, so this is just a small way to reduce traffic on roads and maybe even find a slightly more direct path.

minerCarts in MIningMission are using the `offRoad: true` traveler option when they are traveling to the source, which implements this behavior.

**Comment by jamesgraves** [comment]
Ah, very good.
