### ISSUE TITLE
Link going unfilled for myBase_upgrader

### ISSUE THREAD

**Issue by jamesgraves** [jamesgraves/bonzAI#7]
Somewhere around tick 18596275, the link next to myBase_upgrader_48 stopped getting filled.  So the upgrader ran out of power, and was just sitting there.  And the room controller has started degrading.

Now we have two upgraders sitting near the link, doing nothing because they have no energy.

**Comment by jamesgraves** [comment]
So it seems the conduit creep was out of position.  It seemed like the igor creep was in the destination position the conduit needed to be.  And perhaps the conduit creep was blocking the igor. So this prevented the conduit from filling the link.  

I temporarily killed the igor and modified the memory of the conduit to indicate that it was out of position.  It then moved into the correct position, and started transferring energy to the link.

After the link was filled, the transfers (and room controller upgrades) continued normally.

I think at least part of the problem is that the base is too crowded in that area.  The path object on the conduit creep didn't indicate that it was blocked.  I'm not sure what was going on there.

**Comment by jamesgraves** [comment]
Several things to note.

As part of my debugging process, I did destroy one of the two link structures in the base, because I though that was causing a problem.  But that didn't seem to help.

So with Igor, it will use moveItOrLoseIt to go to its idle position, which will then destroy the conduit creep that is doing is actual job there.  I've been looking at the code for determining the idle position for Igor, but I don't quite understand it yet.  I've put in a hard-coded hack to deal with this temporarily.  I've also previously tried to disable the IgorMission, but that seemed to cause misbehavior too.

We could just change how the conduit works.  Given that the link has a cooldown for each transfer, the link and the storage don't need to be a fixed two squares away from each other.  If they were a little further apart, the conduit creep would have enough time to transfer energy around, like the mining carts do, instead of just sitting in a fixed position and doing transfers / withdrawals.

Another thing to do would be to monitor how long and / or how often the links are empty, and log that to the console.

Another thing is to check the return values of the transfer and withdraw functions, which will indicate a problem.

**Comment by bonzaiferroni** [comment]
Someone else was reporting Igor moving the conduit creep out of position, this was a bug that I introduced when I decided to make Igor's position more "fuzzy".

In both of my layouts, there is actually a place just for Igor, he was just taking conduit's place because of the bug. I thought that I had fixed this so if you are still seeing it, that might not be the case. Either way, the bug almost certainly lies in IgorMission's `findIgorPosition` function.

The rationale behind keeping conduit stationary is there is just a lot less cpu needed for a creep that doesn't have to move.

**Comment by jamesgraves** [comment]
Fixed with: bonzaiferroni/bonzAI@770111eb1dbde1fa2e8fc663727f1343c0f5cd75  Thanks!

I had been running on `master` at the time this issue had appeared.

As I figure out the codebase (and TypeScript), I do anticipate adding some checks for things like a link going unfilled, and logging an error on the console or sending an alert.
